dataPath = '../datasets/';
datasetName = {'CiteSeer', 'BBCSport', 'MSRC_v1', 'Reuters', 'Reuters_21578', ...
    'NUS_WIDE','ALOI_100', 'Yale', 'ORL', 'Caltech101', ...
    'YALE32', 'COIL20','Caltech101-20', 'Caltech101-7','3sources', ...
    'scene-15_3v','100leaves_3v', 'Hdigit', 'NGs','HW', ...
    'HW2sources','LGG','BRCA','CESC', 'ACM',...
    'DBLP','Cifar10_test_4deep','Caltech101_4deep','Number123456','NH_p4660',...
    'C101_p1474','COIL_20_ZCQ','BBC','WebKB'};
metricName = {'cosine' ,'cosine', 'squaredeuclidean', 'cosine', 'cosine', ...
    'squaredeuclidean', 'squaredeuclidean', 'squaredeuclidean', 'squaredeuclidean','squaredeuclidean', ...
    'squaredeuclidean', 'squaredeuclidean','squaredeuclidean', 'squaredeuclidean', 'cosine', ...
    'squaredeuclidean','squaredeuclidean','squaredeuclidean', 'squaredeuclidean','squaredeuclidean', ...
    'squaredeuclidean','squaredeuclidean','squaredeuclidean','squaredeuclidean','squaredeuclidean',...
    'squaredeuclidean','squaredeuclidean','squaredeuclidean', 'squaredeuclidean','squaredeuclidean',...
    'squaredeuclidean', 'squaredeuclidean', 'squaredeuclidean', 'squaredeuclidean'};


